// SPDX-License-Identifier: MIT
/**
 * Wallet bootstrapping and funding.
 *
 * Funding a Midnight wallet is a two-step process: the account needs NIGHT
 * (unshielded tokens, obtained from the faucet on test networks) and it needs
 * DUST (the fee resource, generated by registering NIGHT UTXOs). Both steps are
 * handled here so the deploy and verify scripts can just ask for a funded
 * wallet.
 */

import { waitForFunds, type EnvironmentConfiguration } from '@midnight-ntwrk/testkit-js';
import type { Logger } from 'pino';

import type { NetworkConfig, WalletSecret } from './config.js';
import { MidnightWalletProvider, syncWallet } from './wallet.js';

const syncTimeoutMs = (): number =>
  Number(process.env['MIDNIGHT_SYNC_TIMEOUT_MS'] ?? 60 * 60_000);

/** Build the wallet from `secret`, start it, and wait for it to reach the chain tip. */
export const buildWalletAndSync = async (
  logger: Logger,
  env: EnvironmentConfiguration,
  secret: WalletSecret,
): Promise<MidnightWalletProvider> => {
  const wallet = await MidnightWalletProvider.build(logger, env, secret);
  await wallet.start();
  await syncWallet(logger, wallet.wallet, syncTimeoutMs());
  return wallet;
};

/** Bech32m unshielded address of the wallet (the address the faucet fills). */
export const unshieldedAddress = (wallet: MidnightWalletProvider): string =>
  wallet.unshieldedKeystore.getBech32Address().toString();

/**
 * Ensure the wallet holds NIGHT, dripping from the network faucet when it is
 * empty and the network exposes a drip endpoint, then register NIGHT UTXOs so
 * the wallet can pay fees in DUST.
 *
 * Returns the NIGHT balance observed after the attempt.
 */
export const ensureFunded = async (
  logger: Logger,
  wallet: MidnightWalletProvider,
  config: NetworkConfig,
  env: EnvironmentConfiguration,
): Promise<bigint> => {
  const useFaucet = config.name !== 'local';

  if (useFaucet) {
    logger.info(`Requesting funds from the '${config.name}' faucet if the wallet is empty...`);
  }

  const balance = await waitForFunds(wallet.wallet, env, useFaucet, wallet.unshieldedKeystore);
  logger.info(`NIGHT balance on '${config.name}': ${balance}`);
  return balance;
};

export type FaucetDripResult = {
  readonly ok: boolean;
  readonly status?: number;
  readonly detail: string;
};

/**
 * Call the network's drip API directly.
 *
 * Preview and Preprod gate the *browser* faucet behind a Cloudflare Turnstile
 * challenge, but the drip endpoint itself accepts a JSON body of
 * `{ recipientAddress, amount }`, the same call the official testkit makes. If
 * the endpoint requires a captcha token, supply one via `TURNSTILE_HEADER`.
 */
export const requestFaucetDrip = async (
  logger: Logger,
  config: NetworkConfig,
  recipientAddress: string,
  amount = '1000',
): Promise<FaucetDripResult> => {
  if (!config.faucetApi) {
    const detail = `Network '${config.name}' has no programmatic faucet endpoint.`;
    logger.warn(detail);
    return { ok: false, detail };
  }

  logger.info(`POST ${config.faucetApi} for ${recipientAddress}`);
  try {
    const response = await fetch(config.faucetApi, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Captcha-Token': process.env['TURNSTILE_HEADER'] ?? 'XXXX.DUMMY.TOKEN.XXXX',
        'x-turnstile-token': process.env['TURNSTILE_HEADER'] ?? '',
      },
      body: JSON.stringify({ recipientAddress, amount }),
    });
    const text = await response.text();
    const detail = `${response.status} ${response.statusText} ${text}`.trim();
    logger.info(`Faucet response: ${detail}`);
    return { ok: response.ok, status: response.status, detail };
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    logger.warn(`Faucet request failed: ${detail}`);
    return { ok: false, detail };
  }
};
