// SPDX-License-Identifier: MIT
/**
 * Wallet bootstrapping and funding.
 *
 * Funding a Midnight wallet is a two-step process: the account needs NIGHT
 * (unshielded tokens, obtained from the faucet on test networks) and it needs
 * DUST (the fee resource, generated by registering NIGHT UTXOs). Both steps are
 * handled here so the deploy and verify scripts can just ask for a funded
 * wallet.
 *
 * The second half of this module answers the same question from the outside: it
 * reads an address's unshielded history off the indexer subscription, which is
 * how you confirm a drip landed without paying for a full wallet sync.
 */

import { waitForFunds, type EnvironmentConfiguration } from '@midnight-ntwrk/testkit-js';
import type { FacadeState } from '@midnight-ntwrk/wallet-sdk';
import type { Logger } from 'pino';
import * as Rx from 'rxjs';
import WebSocket from 'ws';

import type { NetworkConfig, WalletSecret } from './config.js';
import { MidnightWalletProvider, syncWallet } from './wallet.js';

const syncTimeoutMs = (): number =>
  Number(process.env['MIDNIGHT_SYNC_TIMEOUT_MS'] ?? 60 * 60_000);

/** Build the wallet from `secret`, start it, and wait for it to reach the chain tip. */
export const buildWalletAndSync = async (
  logger: Logger,
  env: EnvironmentConfiguration,
  secret: WalletSecret,
): Promise<MidnightWalletProvider> => {
  const wallet = await MidnightWalletProvider.build(logger, env, secret);
  await wallet.start();
  await syncWallet(logger, wallet.wallet, syncTimeoutMs());
  return wallet;
};

/** Bech32m unshielded address of the wallet (the address the faucet fills). */
export const unshieldedAddress = (wallet: MidnightWalletProvider): string =>
  wallet.unshieldedKeystore.getBech32Address().toString();



/** NIGHT the wallet's synced state currently shows (the native token's raw type is all zeros). */
const walletNightBalance = (state: FacadeState): bigint =>
  state.unshielded.balances[NIGHT_TOKEN_TYPE] ?? 0n;

const dustSettleTimeoutMs = (): number =>
  Number(process.env['MIDNIGHT_DUST_SETTLE_TIMEOUT_MS'] ?? 180_000);

/**
 * Wait for a dust registration that the testkit just submitted to land.
 *
 * `waitForFunds` registers the wallet's NIGHT UTXOs for dust generation when it
 * holds none, and that transaction spends the NIGHT UTXO before re-creating it
 * in the same transaction. The balance `waitForFunds` returns - and the wallet's
 * own view point - can read 0 NIGHT / 0 DUST for a funded wallet until it
 * settles, which previously made a funded deploy look unfunded. Watch the
 * wallet's state stream until the NIGHT and spendable dust are both back, then
 * report the reclaimed NIGHT balance (0 if it never settles within the timeout).
 */
const awaitDustRegistrationSettlement = async (
  logger: Logger,
  wallet: MidnightWalletProvider,
): Promise<bigint> => {
  const timeout = dustSettleTimeoutMs();
  logger.info(`NIGHT is not visible yet; waiting up to ${timeout}ms for dust registration to settle...`);
  try {
    const settled = await Rx.firstValueFrom(
      wallet.wallet.state().pipe(
        Rx.tap((state) =>
          logger.info(
            `settling: NIGHT=${walletNightBalance(state)} dustCoins=${state.dust.availableCoins.length}`,
          ),
        ),
        Rx.filter(
          (state) => walletNightBalance(state) > 0n && state.dust.availableCoins.length > 0,
        ),
        Rx.timeout({
          each: timeout,
          with: () =>
            Rx.throwError(() => new Error(`dust registration did not settle within ${timeout}ms`)),
        }),
      ),
    );
    return walletNightBalance(settled);
  } catch (error) {
    logger.warn(
      `Dust registration did not settle: ${error instanceof Error ? error.message : String(error)}`,
    );
    return 0n;
  }
};

/**
 * Ensure the wallet holds NIGHT, dripping from the network faucet when it is
 * empty and the network exposes a drip endpoint, then register NIGHT UTXOs so
 * the wallet can pay fees in DUST.
 *
 * Returns the NIGHT balance observed after the attempt.
 */
export const ensureFunded = async (
  logger: Logger,
  wallet: MidnightWalletProvider,
  config: NetworkConfig,
  env: EnvironmentConfiguration,
): Promise<bigint> => {
  const useFaucet = config.name !== 'local';

  if (useFaucet) {
    logger.info(`Requesting funds from the '${config.name}' faucet if the wallet is empty...`);
  }

  // Note the balance before the testkit's flow runs. If the wallet holds NIGHT
  // now but reports none afterwards, the dip is the dust-registration side
  // effect handled below, not an actually unfunded wallet.
  const hadNight = walletNightBalance(await Rx.firstValueFrom(wallet.wallet.state())) > 0n;

  let balance: bigint;
  try {
    balance = await waitForFunds(wallet.wallet, env, useFaucet, wallet.unshieldedKeystore);
  } catch (error) {
    // The faucet can legitimately refuse a programmatic drip (its public API is
    // captcha-gated). That must not crash the run here: re-read the balance
    // without the faucet and let the caller decide with an actionable message.
    const detail = error instanceof Error ? error.message : String(error);
    logger.warn(`Faucet request did not succeed (${detail}); continuing with the current balance.`);
    balance = await waitForFunds(wallet.wallet, env, false, wallet.unshieldedKeystore);
  }

  // When the wallet had NIGHT but `waitForFunds` registered its UTXOs for dust
  // generation, that registration spends the NIGHT UTXO and the value it returns
  // (and the state right after) can read 0 until the transaction settles. Wait
  // for the settlement instead of misreporting the wallet as unfunded.
  if (balance === 0n && hadNight) {
    balance = await awaitDustRegistrationSettlement(logger, wallet);
  }

  logger.info(`NIGHT balance on '${config.name}': ${balance}`);

  if (balance === 0n && config.faucetPage) {
    throw new Error(
      `Wallet is unfunded on '${config.name}'. Fund the address with tNIGHT via ` +
        `${config.faucetPage} (the public drip API requires a browser-solved captcha), ` +
        `then re-run. The faucet must fill the unshielded address printed by ` +
        `scripts/derive-address.ts.`,
    );
  }

  return balance;
};

export type FaucetDripResult = {
  readonly ok: boolean;
  readonly status?: number;
  readonly detail: string;
};

/**
 * Call the network's drip API directly.
 *
 * Preview and Preprod gate the *browser* faucet behind a Cloudflare Turnstile
 * challenge, but the drip endpoint itself accepts a JSON body of
 * `{ recipientAddress, amount }`, the same call the official testkit makes. If
 * the endpoint requires a captcha token, supply one via `TURNSTILE_HEADER`.
 */
export const requestFaucetDrip = async (
  logger: Logger,
  config: NetworkConfig,
  recipientAddress: string,
  amount = '1000',
): Promise<FaucetDripResult> => {
  if (!config.faucetApi) {
    const detail = `Network '${config.name}' has no programmatic faucet endpoint.`;
    logger.warn(detail);
    return { ok: false, detail };
  }

  logger.info(`POST ${config.faucetApi} for ${recipientAddress}`);
  try {
    const response = await fetch(config.faucetApi, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Captcha-Token': process.env['TURNSTILE_HEADER'] ?? 'XXXX.DUMMY.TOKEN.XXXX',
        'x-turnstile-token': process.env['TURNSTILE_HEADER'] ?? '',
      },
      body: JSON.stringify({ recipientAddress, amount }),
    });
    const text = await response.text();
    const detail = `${response.status} ${response.statusText} ${text}`.trim();
    logger.info(`Faucet response: ${detail}`);
    return { ok: response.ok, status: response.status, detail };
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    logger.warn(`Faucet request failed: ${detail}`);
    return { ok: false, detail };
  }
};

// ---------------------------------------------------------------------------
// Ledger-side funding checks
// ---------------------------------------------------------------------------

/**
 * The all-zero token type is the network's native token: NIGHT (`tNIGHT` on the
 * test networks). Any other token type is a user-defined asset.
 */
export const NIGHT_TOKEN_TYPE = '0'.repeat(64);

/** An unshielded token output, as the indexer reports it. */
export type UnshieldedUtxo = {
  readonly owner: string;
  readonly tokenType: string;
  readonly value: bigint;
  readonly outputIndex: number;
  readonly intentHash: string;
};

/** A NIGHT output credited to the watched address; a faucet drip is one of these. */
export type UnshieldedCredit = {
  readonly value: bigint;
  readonly transactionId: number;
  readonly hash: string;
  /** Block timestamp, in milliseconds since the epoch. */
  readonly timestamp: number;
};

/** One message from the `unshieldedTransactions` subscription. */
export type UnshieldedEvent =
  | {
      readonly kind: 'transaction';
      readonly transactionId: number;
      readonly hash: string;
      readonly timestamp: number;
      readonly created: readonly UnshieldedUtxo[];
      readonly spent: readonly UnshieldedUtxo[];
    }
  | { readonly kind: 'progress'; readonly highestTransactionId: number };

/** Fold state while an address's unshielded history is replayed. */
export type UnshieldedLedgerState = {
  readonly unspent: ReadonlyMap<string, UnshieldedUtxo>;
  readonly created: bigint;
  readonly spent: bigint;
  readonly credits: readonly UnshieldedCredit[];
  readonly transactionsSeen: number;
  readonly highestTransactionId: number;
  readonly lastTransactionId: number;
};

/** The answer to "is this address funded?". */
export type UnshieldedBalance = {
  readonly address: string;
  /** NIGHT the address still controls - the number the question turns on. */
  readonly balance: bigint;
  readonly created: bigint;
  readonly spent: bigint;
  readonly unspentOutputs: number;
  readonly credits: readonly UnshieldedCredit[];
  readonly transactionsSeen: number;
  readonly highestTransactionId: number;
  /** True once the indexer has replayed the address's history up to its tip. */
  readonly caughtUp: boolean;
  readonly tipHeight: number | null;
};

export type WatchUnshieldedOptions = {
  /** Keep the stream open until NIGHT arrives, rather than answering once the replay is done. */
  readonly waitForFunding?: boolean;
  /** Quiet period (ms) after the last transaction before a one-shot answer is final. */
  readonly idleMs?: number;
  /** Overall budget (ms). */
  readonly timeoutMs?: number;
  /** Chain tip to record in the result; see `readTipHeight`. */
  readonly tipHeight?: number | null;
  /** Called for every message, so callers can stream progress to a console. */
  readonly onEvent?: (event: UnshieldedEvent) => void;
};

const GRAPHQL_WS_PROTOCOL = 'graphql-transport-ws';
const SUBSCRIPTION_ID = 'unshielded-balance';

/**
 * Replays one address's unshielded history. The indexer streams only that
 * address's transactions (and progress markers), which is why this is cheap
 * compared with scanning blocks or syncing the whole wallet.
 */
const UNSUBSCRIPTION_QUERY = `
  subscription UnshieldedBalance($address: UnshieldedAddress!) {
    unshieldedTransactions(address: $address) {
      __typename
      ... on UnshieldedTransaction {
        transaction { id hash block { timestamp } }
        createdUtxos { owner tokenType value outputIndex intentHash }
        spentUtxos { owner tokenType value outputIndex intentHash }
      }
      ... on UnshieldedTransactionsProgress { highestTransactionId }
    }
  }
`;

type WireUtxo = {
  readonly owner?: unknown;
  readonly tokenType?: unknown;
  readonly value?: unknown;
  readonly outputIndex?: unknown;
  readonly intentHash?: unknown;
};

type WireNode = {
  readonly __typename?: unknown;
  readonly transaction?: {
    readonly id?: unknown;
    readonly hash?: unknown;
    readonly block?: { readonly timestamp?: unknown } | null;
  } | null;
  readonly createdUtxos?: readonly WireUtxo[] | null;
  readonly spentUtxos?: readonly WireUtxo[] | null;
  readonly highestTransactionId?: unknown;
};

const toBigInt = (value: unknown): bigint => {
  try {
    return BigInt(String(value ?? '0'));
  } catch {
    return 0n;
  }
};

const toUtxo = (wire: WireUtxo): UnshieldedUtxo => ({
  owner: String(wire.owner ?? ''),
  tokenType: String(wire.tokenType ?? ''),
  value: toBigInt(wire.value),
  outputIndex: Number(wire.outputIndex ?? 0),
  intentHash: String(wire.intentHash ?? ''),
});

/**
 * GraphQL errors arrive either as a `payload.errors` array or as the payload of
 * an `error` message; both mean the subscription itself was rejected. The
 * indexer reports a bad address this way (e.g. a Preview address asked of
 * Preprod: "expected HRP mn_addr_preprod, but was mn_addr_preview"), which must
 * not be mistaken for "no history".
 */
const extractSubscriptionErrors = (payload: unknown): string[] => {
  const errors = (payload as { errors?: unknown } | null)?.errors;
  if (!Array.isArray(errors)) return [];
  return errors.map((error) => {
    const message = (error as { message?: unknown } | null)?.message;
    return typeof message === 'string' ? message : JSON.stringify(error);
  });
};

const parseUnshieldedEvent = (payload: unknown): UnshieldedEvent | null => {
  const node = (payload as { data?: { unshieldedTransactions?: WireNode } } | null)?.data
    ?.unshieldedTransactions;
  if (!node) return null;

  if (node.__typename === 'UnshieldedTransactionsProgress') {
    return { kind: 'progress', highestTransactionId: Number(node.highestTransactionId ?? 0) };
  }

  const transaction = node.transaction ?? null;
  return {
    kind: 'transaction',
    transactionId: Number(transaction?.id ?? 0),
    hash: String(transaction?.hash ?? ''),
    timestamp: Number(transaction?.block?.timestamp ?? 0),
    created: (node.createdUtxos ?? []).map(toUtxo),
    spent: (node.spentUtxos ?? []).map(toUtxo),
  };
};

/** An output is identified by the intent that created it plus its index. */
const utxoKey = (utxo: UnshieldedUtxo): string => `${utxo.intentHash}:${utxo.outputIndex}`;

const isNightUtxo = (utxo: UnshieldedUtxo, address: string): boolean =>
  utxo.owner === address && utxo.tokenType === NIGHT_TOKEN_TYPE;

export const emptyLedgerState = (): UnshieldedLedgerState => ({
  unspent: new Map(),
  created: 0n,
  spent: 0n,
  credits: [],
  transactionsSeen: 0,
  highestTransactionId: 0,
  lastTransactionId: 0,
});

/**
 * Fold one subscription message into the address's ledger state. Only NIGHT
 * outputs owned by `address` affect the balance; everything else is ignored.
 */
export const applyUnshieldedEvent = (
  state: UnshieldedLedgerState,
  event: UnshieldedEvent,
  address: string,
): UnshieldedLedgerState => {
  if (event.kind === 'progress') {
    return event.highestTransactionId <= state.highestTransactionId
      ? state
      : { ...state, highestTransactionId: event.highestTransactionId };
  }

  const unspent = new Map(state.unspent);
  const credits = [...state.credits];
  let created = state.created;
  let spent = state.spent;

  for (const utxo of event.created) {
    if (!isNightUtxo(utxo, address)) continue;
    unspent.set(utxoKey(utxo), utxo);
    created += utxo.value;
    credits.push({
      value: utxo.value,
      transactionId: event.transactionId,
      hash: event.hash,
      timestamp: event.timestamp,
    });
  }

  for (const utxo of event.spent) {
    if (!isNightUtxo(utxo, address)) continue;
    unspent.delete(utxoKey(utxo));
    spent += utxo.value;
  }

  return {
    unspent,
    created,
    spent,
    credits,
    transactionsSeen: state.transactionsSeen + 1,
    highestTransactionId: state.highestTransactionId,
    lastTransactionId: Math.max(state.lastTransactionId, event.transactionId),
  };
};

/** Turn folded state into the reported answer. */
export const toUnshieldedBalance = (
  state: UnshieldedLedgerState,
  address: string,
  tipHeight: number | null,
  caughtUp: boolean,
): UnshieldedBalance => ({
  address,
  balance: [...state.unspent.values()].reduce((sum, utxo) => sum + utxo.value, 0n),
  created: state.created,
  spent: state.spent,
  unspentOutputs: state.unspent.size,
  credits: state.credits,
  transactionsSeen: state.transactionsSeen,
  highestTransactionId: state.highestTransactionId,
  caughtUp,
  tipHeight,
});

/** Height of the indexer's current chain tip. */
export const readTipHeight = async (config: NetworkConfig): Promise<number> => {
  const response = await fetch(config.indexer, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: '{ block { height } }' }),
  });
  if (!response.ok) {
    throw new Error(`Indexer ${config.indexer} returned ${response.status} ${response.statusText}.`);
  }

  const body = (await response.json()) as { data?: { block?: { height?: unknown } } };
  const height = Number(body.data?.block?.height);
  if (!Number.isFinite(height)) {
    throw new Error(`Indexer ${config.indexer} did not report a block height.`);
  }
  return height;
};

/**
 * Replay `address`'s unshielded history over the indexer's
 * `unshieldedTransactions` subscription - the same feed the wallet SDK syncs
 * with - and report its NIGHT balance.
 *
 * Resolves once the replay is `caughtUp` and has been quiet for `idleMs`, or, in
 * `waitForFunding` mode, as soon as a NIGHT credit lands (the stream then stays
 * open until `timeoutMs`, which makes this usable as a faucet watcher). Rejects
 * only if the subscription cannot be established or fails outright; a timeout or
 * a dropped connection resolves with `caughtUp: false`, which means the balance
 * is a lower bound rather than the whole truth.
 */
export const watchUnshieldedBalance = async (
  config: NetworkConfig,
  address: string,
  options: WatchUnshieldedOptions = {},
): Promise<UnshieldedBalance> => {
  const idleMs = options.idleMs ?? 5_000;
  const timeoutMs = options.timeoutMs ?? 180_000;

  return await new Promise<UnshieldedBalance>((resolve, reject) => {
    let state = emptyLedgerState();
    let sawProgress = false;
    let caughtUp = false;
    let settled = false;
    let lastTransactionAt = Date.now();
    let poll: NodeJS.Timeout | undefined;
    let deadline: NodeJS.Timeout | undefined;

    const socket = new WebSocket(config.indexerWS, GRAPHQL_WS_PROTOCOL);

    const updateCaughtUp = (): void => {
      if (!sawProgress) return;
      // A highestTransactionId of 0 means the address has no history at all.
      caughtUp = state.highestTransactionId === 0 || state.lastTransactionId >= state.highestTransactionId;
    };

    const settle = (error?: unknown): void => {
      if (settled) return;
      settled = true;
      if (poll) clearInterval(poll);
      if (deadline) clearTimeout(deadline);
      socket.terminate();
      if (error === undefined) {
        resolve(toUnshieldedBalance(state, address, options.tipHeight ?? null, caughtUp));
      } else {
        reject(error instanceof Error ? error : new Error(String(error)));
      }
    };

    socket.on('open', () => socket.send(JSON.stringify({ type: 'connection_init' })));
    socket.on('error', (error) => settle(error));
    socket.on('close', () => {
      // Closed before we finished replaying: report what we saw, flagged partial.
      updateCaughtUp();
      settle();
    });

    socket.on('message', (raw) => {
      let message: { type?: unknown; payload?: unknown };
      try {
        message = JSON.parse(String(raw)) as typeof message;
      } catch {
        return;
      }

      switch (typeof message.type === 'string' ? message.type : '') {
        case 'connection_ack':
          socket.send(
            JSON.stringify({
              id: SUBSCRIPTION_ID,
              type: 'subscribe',
              payload: { query: UNSUBSCRIPTION_QUERY, variables: { address } },
            }),
          );
          return;
        case 'ping':
          socket.send(JSON.stringify({ type: 'pong' }));
          return;
        case 'next': {
          const errors = extractSubscriptionErrors(message.payload);
          if (errors.length > 0) {
            settle(new Error(`Indexer rejected the subscription: ${errors.join('; ')}`));
            return;
          }

          const event = parseUnshieldedEvent(message.payload);
          if (!event) return;
          state = applyUnshieldedEvent(state, event, address);
          if (event.kind === 'progress') sawProgress = true;
          else lastTransactionAt = Date.now();
          updateCaughtUp();
          options.onEvent?.(event);
          return;
        }
        case 'error': {
          const errors = extractSubscriptionErrors(message.payload);
          settle(
            new Error(
              `Indexer subscription failed: ${errors.length > 0 ? errors.join('; ') : JSON.stringify(message.payload)}`,
            ),
          );
          return;
        }
        case 'complete':
          updateCaughtUp();
          settle();
          return;
        default:
          return;
      }
    });

    poll = setInterval(() => {
      if (settled) return;
      const funded = state.unspent.size > 0;

      if (options.waitForFunding) {
        // The question was "has a drip landed yet", so the first credit answers it.
        if (funded) settle();
        return;
      }

      // Give the stream `idleMs` of quiet (since the last transaction, so a
      // steady drip of progress markers cannot stall us) before finalising.
      if (caughtUp && Date.now() - lastTransactionAt >= idleMs) settle();
    }, 250);

    deadline = setTimeout(() => settle(), timeoutMs);
  });
};
